services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=myPass123
      - POSTGRES_USER=librarian
      - POSTGRES_DB=library