spring:
  application:
    name: demo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: librarian
    password: myPass123


